Perform changelong and version checks on CI, not CD

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,6 +12,8 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 2
 
       - name: Setup pnpm
         uses: pnpm/action-setup@v4
@@ -24,6 +26,23 @@ jobs:
 
       - name: Install dependencies
         run: pnpm install
+
+      - name: Check for version increment
+        run: |
+          LOCAL_VERSION=$(jq -r .version package.json)
+          NPM_VERSION=$(npm view . version)
+          if [ "$LOCAL_VERSION" == "$NPM_VERSION" ]; then
+            echo "Error: Version has not been incremented."
+            exit 1
+          fi
+
+      - name: Check for changelog update
+        run: |
+          git diff HEAD~1 HEAD --name-only | grep -q "CHANGELOG.md"
+          if [ $? -ne 0 ]; then
+            echo "Error: CHANGELOG.md has not been updated."
+            exit 1
+          fi
 
       - name: Run formatter
         run: pnpm format
